language: python
python:
  - 2.6
  - 2.7
  - 3.3
env: HTTPBIN_URL=http://httpbin.org/
script:
  - python test_requests.py
install:
  - python setup.py install
  - pip install -e .[extra]
notifications:
  email: false
