sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "3.7-dev"
  # - "pypy"  -- appears to hang
  # - "pypy3"
# command to install dependencies
install: "make"
# command to run tests
script:
  - make test-readme
  - make ci
cache: pip
jobs:
  include:
    - stage: test
      script:
        - make test-readme
        - make ci
    - stage: coverage
      python: 3.6
      script: codecov
